### ISSUE TITLE
infinitely recurring function causing segfault

### ISSUE THREAD

**Issue by sir-murray** [ashinn/chibi-scheme#371]
```
λ ./chibi-scheme 
> (define f (lambda (a) (+ a (f (+ a 1)))))
> (f 1)
ERROR: out of stack space
Segmentation fault (core dumped)
```

Built on archlinux with default options at 50d7cedb3f13a157ad24789daae24db6759eaa38

When I try it directly in gdb, it works fine.
Coredump looks like this:

```
Core was generated by `./chibi-scheme'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0663c8572c in sexp_stack_trace (ctx=ctx@entry=0x7f06631ab060, out=0x7f066276ca20) at vm.c:51
51          if (self && sexp_procedurep(self)) {
(gdb) bt
#0  0x00007f0663c8572c in sexp_stack_trace (ctx=ctx@entry=0x7f06631ab060, out=0x7f066276ca20) at vm.c:51
#1  0x00000000004046a9 in repl (env=0x7f066276ca80, ctx=0x7f06631ab060) at main.c:157
#2  run_main (argc=argc@entry=1, argv=argv@entry=0x7ffdd8190958) at main.c:521
#3  0x00000000004017aa in main (argc=1, argv=0x7ffdd8190958) at main.c:622
(gdb) list
46        sexp self, bc, src, *stack=sexp_stack_data(sexp_context_stack(ctx));
47        if (! sexp_oportp(out))
48          out = sexp_current_error_port(ctx);
49        for (i=fp; i>4; i=sexp_unbox_fixnum(stack[i+3])) {
50          self = stack[i+2];
51          if (self && sexp_procedurep(self)) {
52            sexp_write_string(ctx, "  called from ", out);
53            bc = sexp_procedure_code(self);
54            if (sexp_symbolp(sexp_bytecode_name(bc)))
55              sexp_write(ctx, sexp_bytecode_name(bc), out);
(gdb) p i
$1 = 1023496
(gdb) x self
0xffc88348018964d8:     Cannot access memory at address 0xffc88348018964d8
(gdb) p (ctx->value.context.stack)->value.stack
$2 = {length = 1024, top = 0, data = 0x7f06631bd918}
```
i dont really know whats useful here, im just guessing.

the `sexp` type confused me for a minute because its got the * in the typedef.

**Comment by ashinn** [comment]
We're actually detecting the out-of-stack error correctly, but when trying to print the trace the stack is already corrupt.  I've disabled stack traces in the OOS case.
