### ISSUE TITLE
chibi-scheme 0.7.3 segfaults on Ubuntu 14.04

### ISSUE THREAD

**Issue by jbulow** [ashinn/chibi-scheme#377]
```
make
sudo make install PREFIX=/some/path
/some/path/bin/chibi-scheme
Segmentation fault
...
(gdb) bt full
#0  0x00007ffff7bc0272 in sexp_env_cell_loc1 (varenv=0x0, localp=1, key=0x735072c6, env=0x7ffff70da620) at eval.c:85
        ls = 0x0
#1  sexp_env_cell_loc (ctx=ctx@entry=0x7ffff70c5060, env=env@entry=0x7ffff70da620, key=key@entry=0x735072c6, localp=localp@entry=1, varenv=varenv@entry=0x0) at eval.c:109
        cell = <optimized out>
        ls = <optimized out>
#2  0x00007ffff7bc0488 in sexp_env_cell (ctx=ctx@entry=0x7ffff70c5060, env=env@entry=0x7ffff70da620, key=key@entry=0x735072c6, localp=localp@entry=1) at eval.c:120
No locals.
#3  0x00007ffff7bc04ea in sexp_env_define (ctx=ctx@entry=0x7ffff70c5060, env=0x7ffff70da620, key=0x735072c6, value=0x10e) at eval.c:176
        cell = <optimized out>
        tmp = <optimized out>
        value = 0x10e
        key = 0x735072c6
        env = 0x7ffff70da620
        ctx = 0x7ffff70c5060
#4  0x0000000000402163 in sexp_load_standard_repl_env (ctx=ctx@entry=0x7ffff70c5060, env=<optimized out>, bootp=bootp@entry=0, k=0x1d) at main.c:353
        e = 0x7ffff70da620
        __sexp_gc_preserver1 = {
          var = 0x7fffffffe398,
          next = 0x7fffffffe500
        }
        sym = 0x735072c6
        __sexp_gc_preserver2 = {
          var = 0x7fffffffe3a0,
          next = 0x7fffffffe3b0
        }
        tmp = 0x10e
        __sexp_gc_preserver3 = {
          var = 0x7fffffffe3a8,
          next = 0x7fffffffe3c0
        }
#5  0x0000000000402609 in run_main (argc=argc@entry=1, argv=argv@entry=0x7fffffffe6e8) at main.c:601
        impmod = <optimized out>
        arg = 0x3d8f538 <error: Cannot access memory at address 0x3d8f538>
        prefix = <optimized out>
        suffix = <optimized out>
        main_symbol = <optimized out>
        main_module = <optimized out>
        i = 1
        j = <optimized out>
        c = <optimized out>
        quit = <optimized out>
        print = <optimized out>
        init_loaded = <optimized out>
        mods_loaded = <optimized out>
        fold_case = <optimized out>
        heap_size = <optimized out>
        heap_max_size = <optimized out>
        out = <optimized out>
        ctx = 0x7ffff70c5060
        tmp = 0x10e
        __sexp_gc_preserver1 = {
          var = 0x7fffffffe480,
          next = 0x0
        }
        sym = 0x10e
        __sexp_gc_preserver2 = {
          var = 0x7fffffffe488,
          next = 0x7fffffffe4d0
        }
        args = 0x8e
        __sexp_gc_preserver3 = {
          var = 0x7fffffffe490,
          next = 0x7fffffffe4e0
        }
        env = 0x7ffff70c8700
        __sexp_gc_preserver4 = {
          var = 0x7fffffffe498,
          next = 0x7fffffffe4f0
        }
#6  0x00000000004019fa in main (argc=1, argv=0x7fffffffe6e8) at main.c:708
No locals.
```

**Comment by ashinn** [comment]
PREFIX needs to be included in the call to "make" as well.
